version: '3'

services:
  app:
    build: .
    volumes:
    - "./src/main/resources/application-dev.properties:/usr/src/mymaven/src/main/application.properties"
    - ".:/usr/src/mymaven"
    - "/usr/src/mymaven/src/main/resources"
    - "/usr/src/mymaven/target"
    ports:
    - 8080:8080

  db:
    image: 'postgres:latest'
    ports:
    - 15432:5432
    environment:
      - POSTGRES_PASSWORD=S@kasaki1123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gerenciador-tarefas
    volumes:
      - /tmp/db-data/:/var/lib/postgresql/data/
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
